spring.application.name=demo-app

# PostgreSQL Connection Configuration
spring.datasource.url=jdbc:postgresql://postgres-service:5432/demo-app
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration (PostgreSQL Dialect)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

spring.messages.basename=i18n/sign_in/sign_in,i18n/sign_up/sign_up
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
spring.messages.always-use-message-format=false

# Log Configuration
logging.level.root=INFO
logging.level.org.springframework.data=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.example.demo_app.controller.LoginController=DEBUG

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Actuator Endpoint Configuration (Exporting Health & Info)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Spring Security Logging Configuration
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web.filter=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.access.intercept.AuthorizationFilter=DEBUG

# Redis Configuration (Kubernetes Service Name)
spring.data.redis.host=redis-service
spring.data.redis.port=6379
