apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - mysite.local
    secretName: mysite-tls-secret
  rules:
  - host: mysite.local
    http:
      paths:
      # Spring Boot REST API
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: springboot-service
            port:
              number: 8080

      # Kibana UI
      - path: /kibana(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kibana-service
            port:
              number: 5601

      # Elasticsearch API (No need ELK port-forward anymore)
      - path: /elasticsearch(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: elasticsearch-service
            port:
              number: 9200

      # React Frontend App
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-app-service
            port:
              number: 80